### ISSUE TITLE
Build a Video Chat with React

### ISSUE THREAD

**Issue by dkundel** [twilio/voices#11]
Show how to integrate [Twilio Video](https://www.twilio.com/video) into a React application.

**Comment by kimobrian** [comment]
@dkundel I guess we can close this. Here's the link to the publication: [Building a Video Chat App with Twilio Programmable Video and React](https://www.twilio.com/blog/2018/03/video-chat-react.html) an d the [Github Repo](https://github.com/kimobrian/TwilioReact).

**Comment by dkundel** [comment]
Good catch @kimobrian. Thank you for contributing to the blog :)
