### ISSUE TITLE
How to Build A Chat Application with Python and Django

### ISSUE THREAD

**Issue by mattmakai** [twilio/voices#13]
Use [Twilio Chat](https://www.twilio.com/docs/api/chat) along with Python and Django to show the reader how to build a chat application.

**Comment by managedkaos** [comment]
I hope to have a submission for this topic complete by the end of this week (Dec 15, 2017).

**Comment by dkundel** [comment]
Awesome @managedkaos! Let me know if I can help you with anything on this.

**Comment by mikigraf** [comment]
@managedkaos are you working on this submission?

**Comment by managedkaos** [comment]
Hey @spejss and @dkundel!  Yes, i have the app and document complete.  I am standing by for review with the Twilio team.  Will update as soon as I can.

**Comment by managedkaos** [comment]
The article has been submitted for review...

**Comment by dkundel** [comment]
Since this moved into the review stage, I'll close this issue. Thanks @managedkaos!
