### ISSUE TITLE
Send an SMS when your YouTube channel goes LIVE (PHP)

### ISSUE THREAD

**Issue by themarcusbattle** [twilio/voices#53]

**Comment by dongido001** [comment]
Yo @themaracusbatle,

Is this still open for grab?

**Comment by themarcusbattle** [comment]
Hey @dongido001 I'm sorry but we actually just published this one yesterday. I hadn't had a chance to close this topic out. It was published here https://www.twilio.com/blog/send-live-streaming-sms-notifications-php-youtube-api

Are you a current Twilio Voices Contributor? I don't see your information in our contributors' list. I'd love to get you to join the program here [https://twiliovoices.com]( https://twiliovoices.com)
